# @baseURL = http://localhost:3000
@baseURL = http://localhost:3000/api

## Category

GET {{baseURL}}/products


###

POST {{baseURL}}/products
Content-Type: application/json

{
    "name": "food",
    "calories": 15,
    "price": 13,
    "category":"chicken",
    "image": {
        "imageURL": "https://res.cloudinary.com/dqqkocsxg/image/upload/v1663595046/cld-sample-5.jpg"
    },
    "quantity": 1
}

###

DELETE {{baseURL}}/products/1
Content-Type: application/json